Hide keyboard input when clicking on ios current datetime entry
skwasjer/skwas-cordova-plugin-datetimepicker pull request #60
Opened 2022-06-20 12:19 UTC by sybers

When using the wheel mode (iOS 14+), if the user clicks on the currently selected datetime it opens a keyboard over the datetime input.

This behaviour looks weird as we don't know what this number input is for as it overlays with the plugin UI.

This PR disables this behaviour by adding a `.editingDidBegin` event handler which calls `resignFirstResponder` on the datetime ui control.

See below video for demo of the initial issue.

https://user-images.githubusercontent.com/15731884/174600055-4e1f6559-2258-444e-a585-5e94560c1f5a.mov

2022-06-20 14:15 UTC, skwasjer requested changes
Thanks for PR, can you have a look at the requested change?

2022-06-20 14:15 UTC, skwasjer commented on src/ios/DateTimePicker.m
> +        [datePicker addTarget:self action:@selector(handleDatePickerTap:) forControlEvents:UIControlEventEditingDidBegin];
Should this rather be moved to `initPickerView`? This method is called on each 'show', and thus registers the delegate each time, which might be leaky, can you confirm?

2022-06-21 08:06 UTC, skwasjer approved these changes

2022-06-22 22:35 UTC, skwasjer commented
I had to patch my CI script (see https://github.com/skwasjer/skwas-cordova-plugin-datetimepicker/pull/61), can you rebase/update PR one time to rerun the pipeline? Then I will accept the PR and release it. Thanks!

2022-06-23 22:31 UTC, merged

2022-06-24 12:43 UTC, sybers commented
Awesome @skwasjer, thanks for your quick response !